server {
    listen 80;
    listen [::]:80;
    server_name example.org;

    # Keep at or above CREATION_MULTIPART_BODY_LIMIT in api/src/common/request.rs.
    client_max_body_size 101M;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name example.org;
    
    server_tokens off;
		
    # Keep at or above CREATION_MULTIPART_BODY_LIMIT in api/src/common/request.rs.
    client_max_body_size 101M;

    ssl_certificate /etc/letsencrypt/live/example.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;

    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3100;
    
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
